project/urls.py
from django.conf.urls import url
from . import views

app_name = 'project'

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^projects/$', views.projects, name='projects'),
    url(r'^applications/$', views.applications, name='applications'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<project_id>[0-9]+)/$', views.project_detail, name='project_detail'),
    url(r'^(?P<project_id>[0-9]+)/application_detail/(?P<application_id>[0-9]+)/$', views.application_detail, name='application_detail'),
    url(r'^(?P<project_id>[0-9]+)/report/$', views.report, name='report'),
    url(r'^create_project/$', views.create_project, name='create_project'),
    url(r'^(?P<project_id>[0-9]+)/delete_project/$', views.delete_project, name='delete_project'),
    url(r'^(?P<project_id>[0-9]+)/create_application/$', views.create_application, name='create_application'),
    url(r'^(?P<project_id>[0-9]+)/delete_application/(?P<application_id>[0-9]+)/$', views.delete_application, name='delete_application'),
    url(r'^setChecklist/$', views.setChecklist, name='setChecklist'),
    url(r'^getChecklist/$', views.getChecklist, name='getChecklist'),
    url(r'^setReportlist/$', views.setReportlist, name='setReportlist'),
    url(r'^getReportlist/$', views.getReportlist, name='getReportlist'),
]

website/urls.py
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^project/', include('project.urls')),
    url(r'^', include('project.urls', namespace="login")),
]

project/models.py
from django.contrib.auth.models import Permission, User
from django.db import models

# Create your models here.


class Project(models.Model):

    user = models.ForeignKey(User, default=1, on_delete=models.SET_DEFAULT, related_name='user')
    name = models.CharField(max_length=100)
    situation = models.CharField(max_length=10)

    def __str__(self):
        return self.name + ' - ' + self.situation


class Application(models.Model):

    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='project')
    name = models.CharField(max_length=100)
    access = models.CharField(max_length=100)
    username = models.CharField(max_length=30)
    notes = models.TextField(max_length=1000)
    checklist = models.CharField(max_length=100)
    reported = models.CharField(max_length=100)

    def __str__(self):
        return self.name + ' - ' + self.access + ' - ' + self.username + ' - ' + self.notes + ' - ' + self.checklist + ' - ' + self.reported

    def usernameInApp(userRequest):
        appList = []
        applications = Application.objects.all()

        for app in applications:
            userInApp = (app.username).split(',')

            for user in userInApp:
                if user == userRequest.user.username:
                    appList.append(app)

        return appList


class CheckList(models.Model):

    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

project/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Project, Application


class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ['name', 'situation']


class ApplicationForm(forms.ModelForm):

    class Meta:
        model = Application
        fields = ['name', 'access', 'username', 'notes']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

project/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .forms import ProjectForm, ApplicationForm, UserForm
from .models import Project, Application, CheckList
# Create your views here.

# This is home page. When user logs in, the page that will be seen


def index(request):
    if not request.user.is_authenticated:  # Does user log in?
        return render(request, 'project/login.html')
    else:
        projects = Project.objects.all()  # Getter all projects
        applications = Application.objects.all()  # Getter all applications

        query = request.GET.get("q")  # Search project

        if query:
            projects = projects.filter(
                Q(name__icontains=query)
            ).distinct()

            return render(request, 'project/index.html', {'projects': projects, 'applications': applications})
        else:
            return render(request, 'project/index.html', {'projects': projects, 'applications': applications})

# This is projects page


def projects(request):
    if not request.user.is_authenticated:  # Does user log in?
        return render(request, 'project/login.html')
    else:
        # BURAYA KULLANICININ YETKİLİ OLDUĞU PROJELER GELECEK.
        projects = Project.objects.all()  # Getter all projects
        return render(request, 'project/projects.html', {'projects': projects})

# This is applications page


def applications(request):
    if not request.user.is_authenticated:  # Does user log in?
        return render(request, 'project/login.html')
    else:
        projects = Project.objects.all()  # Getter all projects
        applications = Application.objects.all()
        # Getter all applications that related with users who logged in
        # BURAYA KULLANICIN YETKİLİ OLDUĞU PROJELER VE UYGULAMALAR LİSTESİ GELECEK.
        #applications = Application.usernameInApp(request)
        return render(request, 'project/applications.html', {'projects': projects, 'applications': applications})

# This is register page


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():  # Is there register form?
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)  # User's password is set
        user.save()  # User's password is saved database
        # User logs in home page
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                projects = Project.objects.all()
                applications = Application.objects.all()
                return render(request, 'project/index.html', {'projects': projects, 'applications': applications})
    context = {
        "form": form,
    }
    return render(request, 'project/register.html', context)

# This is log in page


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                #request.session.set_expiry(300)  # 5 minutes expire session
                projects = Project.objects.all()
                applications = Application.objects.all()
                return render(request, 'project/index.html', {'projects': projects, 'applications': applications})
            else:
                return render(request, 'project/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'project/login.html', {'error_message': 'Invalid login'})
    return render(request, 'project/login.html')

#This is log out


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'project/login.html', context)

# This is project_detail page
# project_id is the project unique id

# BURAYI SADECE PROJEDEKI YETKILI KISILER GOREBILECEK


def project_detail(request, project_id):
    if not request.user.is_authenticated:  # Does user log in?
        return render(request, 'project/login.html')
    else:
        #BURAYA KULLANICININ YETKİLİ OLDUĞU UYGULAMALAR GELECEK.
        project = get_object_or_404(Project, pk=project_id)
        applications = Application.objects.filter(project_id=project.id)

        return render(request, 'project/project_detail.html', {'project': project, 'applications': applications})

# This is applications_detail page
# project_id is the project unique id
# application_id is the application unique id

# BURAYI SADECE UYGULAMAYA YETKILI KISILER GOREBILECEK


def application_detail(request, project_id, application_id):
    if not request.user.is_authenticated:  # Does user log in?
        return render(request, 'project/login.html')
    else:
        project = get_object_or_404(Project, pk=project_id)
        application = get_object_or_404(Application, pk=application_id)
        checklists = CheckList.objects.all()

        checkboxLength = len(checklists)
        table = []

        for i in range(checkboxLength):
            table.append([list(checklists)[i], list(application.checklist)[i]])

        return render(request, 'project/application_detail.html', {'project': project, 'application': application, 'table': table})

#This is for user to see selected project applications and checkboxes together.

# BURAYI PROJEYE YETKILI KISILER GOREBILECEK VE PROJEDE YETKILI OLDUGU UYGULAMALAR GOSTERILECEK


def report(request, project_id):
    if not request.user.is_authenticated:
        return render(request, 'project/login.html')
    else:
        project = get_object_or_404(Project, pk=project_id)
        applications = Application.objects.filter(project_id=project.id)
        checklists = CheckList.objects.all()

        return render(request, 'project/report.html', {'project': project, 'applications': applications, 'checklists': checklists})

#This is for creating projects.


def create_project(request):
    if not request.user.is_authenticated:
        return render(request, 'project/login.html')
    else:
        if request.user.is_superuser:
            form = ProjectForm(request.POST or None)
            if form.is_valid():
                project = form.save(commit=False)
                project.user = request.user
                project.save()
                return render(request, 'project/project_detail.html', {'project': project})
            context = {
                "form": form,
            }
            return render(request, 'project/create_project.html', context)
        else:
            projects = Project.objects.all()
            applications = Application.objects.all()

            return render(request, 'project/index.html', {'projects': projects, 'applications': applications})

#This is for deleting projects.


def delete_project(request, project_id):
    if not request.user.is_authenticated:
        return render(request, 'project/login.html')
    else:
        projects = Project.objects.all()
        applications = Application.objects.all()

        if request.user.is_superuser:
            project = get_object_or_404(Project, pk=project_id)
            project.delete()

            return render(request, 'project/index.html', {'projects': projects, 'applications': applications})
        else:
            return render(request, 'project/index.html', {'projects': projects, 'applications': applications})

#This is for creating application.


def create_application(request, project_id):
    if not request.user.is_authenticated:
        return render(request, 'project/login.html')
    else:
        if request.user.is_superuser:
            form = ApplicationForm(request.POST or None)
            project = get_object_or_404(Project, pk=project_id)
            if form.is_valid():
                Applications = Application.objects.all()
                for apps in Applications:
                    if apps.name == form.cleaned_data.get("name"):
                        context = {
                            'project': project,
                            'form': form,
                            'error_message': 'You already added that application',
                        }
                        return render(request, 'project/create_application.html', context)
                application = form.save(commit=False)
                # User can only create projects that project's user is itself.
                application.project = project

                checklists = CheckList.objects.all()
                checklist = ''

                for check in checklists:
                    checklist = checklist+'0'

                application.checklist = checklist
                application.reported = checklist
                application.save()

                applications = Application.objects.filter(
                    project_id=project.id)

                return render(request, 'project/project_detail.html', {'project': project, 'applications': applications})
            context = {
                'project': project,
                'form': form,
            }
            return render(request, 'project/create_application.html', context)
        else:
            projects = Project.objects.all()
            applications = Application.objects.all()

            return render(request, 'project/index.html', {'projects': projects, 'applications': applications})

#This is for deleting application.


def delete_application(request, project_id, application_id):
    if not request.user.is_authenticated:
        return render(request, 'project/login.html')

project/templates/project/applications.html
{% extends 'project/base.html' %}
{% block title %}Applications{% endblock %}
{% block applications_active %}active{% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1">

            {% for project in projects %}

            <div class="panel panel-default">

                <div class="panel-heading">
                    <div class="row">

                        <div class="col-sm-10">
                            <h3>{{project.name}}</h3>
                        </div>

                    </div>
                </div>

                <div class="panel-body">
                    <div class="row">

                        <div class="table-responsive-sm">
                            <table class="table table-hover">

                                <thead>
                                    <tr>
                                        <th style="width: 2%">
                                            <div class="col-sm-1"></div>
                                        </th>
                                        <th style="width: 3%">
                                            <div class="col-sm-1">#</div>
                                        </th>
                                        <th style="width: 20%">
                                            <div class="col-sm-1">Name</div>
                                        </th>
                                        <th style="width: 15%">
                                            <div class="col-sm-1">Access</div>
                                        </th>
                                        <th style="width: 15%">
                                            <div class="col-sm-1">Users</div>
                                        </th>
                                        <th style="width: 40%">
                                            <div class="col-sm-4">Notes</div>
                                        </th>
                                        <th style="width: 5%">
                                            <div class="col-sm-1"></div>
                                        </th>
                                    </tr>
                                </thead>

                                <tbody>

                                    {% for application in applications %}
                                    {% if application.project.id == project.id %}

                                    <tr>
                                        <td style="width: 2%">
                                            <div class="col-sm-1">
                                                <a href="{% url 'project:delete_application' project.id application.id %}"
                                                    class="btn btn-danger btn-sm">
                                                    <span class="glyphicon glyphicon-remove-sign"></span>
                                                </a>
                                            </div>
                                        </td>
                                        <td style="width: 3%">
                                            <div class="col-sm-1">{{forloop.counter}}</div>
                                        </td>
                                        <td style="width: 15%">
                                            <div class="col-sm-1">
                                                <a
                                                    href="{% url 'project:application_detail' project.id application.id %}">
                                                    {{application.name}}
                                                </a>
                                            </div>
                                        </td>
                                        <td style="width: 15%">
                                            <div class="col-sm-1">{{application.access}}</div>
                                        </td>
                                        <td style="width: 15%">
                                            <div class="col-sm-1">{{application.username}}</div>
                                        </td>
                                        <td style="width: 40%">
                                            <div class="col-sm-4">{{application.notes}}</div>
                                        </td>
                                        <td style="width: 5%">
                                            <div class="col-sm-1">100 %</div>
                                        </td>
                                    </tr>

                                    {% endif %}
                                    {% endfor %}

                                </tbody>

                            </table>

                            <div class="row">
                                <div class="col-sm-10 col-sm-offset-1">

                                    <a href="{% url 'project:create_application' project.id %}"
                                        class="btn btn-success btn-sm">
                                        <span class="glyphicon glyphicon-plus-sign"></span> New Application
                                    </a>

                                </div>
                            </div>

                        </div>

                    </div>
                </div>

            </div>

            {% endfor %}

        </div>
    </div>
</div>

{% endblock %}

project/templates/project/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>{% block title %}Home{% endblock %}</title>
  {% load staticfiles %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="{% static 'project/style.css' %}" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <script src="{% static 'project/js/main.js' %}"></script>
</head>

<body>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">

      <!-- Header -->
      <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'project:index' %}">WebSiteName</a>
      </div>

      <!-- Items -->
      <ul class="nav navbar-nav">
        <li class="{% block projects_active %}{% endblock %}"><a href="{% url 'project:projects' %}">Projects</a></li>
        <li class="{% block applications_active %}{% endblock %}"><a
            href="{% url 'project:applications' %}">Applications</a></li>
      </ul>

      <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'project:index' %}">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search" name="q" value="{{ request.GET.q }}">
          <div class="input-group-btn">
            <button class="btn btn-default" type="submit">
              <i class="glyphicon glyphicon-search"></i>
            </button>
          </div>
        </div>
      </form>

      <ul class="nav navbar-nav navbar-right">
        <li class="{% block user_active %}{% endblock %}"><a href="#">
            <span class="glyphicon glyphicon-user"></span> {{user.username}}</a>
        </li>
        <li class="{% block logout_active %}{% endblock %}"><a href="{% url 'project:logout_user' %}">
            <span class="glyphicon glyphicon-log-out"></span> Log out</a>
        </li>
      </ul>

    </div>
  </nav>

  {% block body %}
  {% endblock %}

</body>

</html>

project/templates/project/base_visitor.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>{% block title %}Home{% endblock %}</title>
  {% load staticfiles %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="{% static 'project/style.css' %}" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <script src="{% static 'project/js/main.js' %}"></script>
</head>

<body>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">

      <!-- Header -->
      <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'project:index' %}">WebSiteName</a>
      </div>

      <!-- Items -->
      <ul class="nav navbar-nav navbar-right">
        <li class="{% block register_active %}{% endblock %}"><a href="{% url 'project:register' %}">
            <span class="glyphicon glyphicon-user"></span> Register</a>
        </li>
        <li class="{% block login_active %}{% endblock %}"><a href="{% url 'project:login_user' %}">
            <span class="glyphicon glyphicon-log-in"></span> Log in</a>
        </li>
      </ul>

    </div>
  </nav>

  {% block body %}
  {% endblock %}

</body>

</html>

project/templates/project/detail.html
{% extends 'project/base.html' %}

{% block body %}
{% if user.is_authenticated%}
<div class="container" style="width: 95%">
  <div class="panel panel-default" style="margin: 50px;">
    <div class="panel-heading">
      <h3>{{project.name}}<h3>
    </div>
    <div class="panel-body">
      <!-- Edit -->
      <a href="#" class="btn btn-warning " style="background-color: orange; border: none; margin: 10px 0px 10px 20px">
        <span class="glyphicon glyphicon-edit" style="background-color: orange"></span> Edit
      </a>
      <!-- Delete -->
      <a href="{% url 'project:delete_project' project.id %}" class="btn btn-danger "
        style="background-color: red; border: none;"
        onclick="return confirm('Are you sure you want to delete this project.')">
        <span class="glyphicon glyphicon-remove-sign" style="background-color: red"></span> Remove
      </a>
      <!-- Info -->
      <a href="#coll" class="btn btn-info" data-toggle="collapse"
        style="background-color:#1996ff; border: none; float:right; margin: 10px 20px 10px 0px">
        <span class="glyphicon glyphicon-info-sign" style="background-color:#1996ff"></span> Info
      </a>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>#</th>
            <th>Firstname</th>
            <th>Lastname</th>
            <th>Age</th>
            <th>City</th>
            <th>Country</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1</td>
            <td>{{project.name}}</td>
            <td>{{project.situation}}</td>
            <td>{{project}}</td>
            <td>New York</td>
            <td>USA</td>
          </tr>
        </tbody>
      </table>
      <p>{{a.id}}</p>
      <div id="coll">
        <p>{{project.name}}</p>
        <p id="demo"></p>
      </div>
      <div style="margin: 30px 0px 10px 30px">
        <a href="{% url 'project:create_application' project.id %}" class="btn btn-success btn-lg" style="border:none">
          <span class="glyphicon glyphicon-plus-sign"></span> Create New Application
        </a>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

project/templates/project/form_template.html
{% for field in form %}

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <span class="text-danger small">{{ field.errors }}</span>
  </div>
  <label class="control-label col-sm-2">{{ field.label_tag }}</label>
  <div class="col-sm-10">{{ field }}</div>
</div>

{% endfor %}

project/templates/project/project_detail.html
{% extends 'project/base.html' %}
{% block title %}{{project.name}}'s Detail{% endblock %}

{% block body %}

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">

      <div class="panel-group">
        <div class="panel panel-default">

          <div class="panel-heading">
            <div class="row">

              <div class="col-sm-10">
                <h3>{{project.name}}'s Detail</h3>
              </div>

            </div>
          </div>

          <div class="panel-body">

            <div class="table-responsive-sm">
              <table class="table table-hover">

                <thead>
                  <tr>
                    <th style="width: 2%">
                      <div class="col-sm-1"></div>
                    </th>
                    <th style="width: 3%">
                      <div class="col-sm-1">#</div>
                    </th>
                    <th style="width: 20%">
                      <div class="col-sm-1">Name</div>
                    </th>
                    <th style="width: 15%">
                      <div class="col-sm-1">Access</div>
                    </th>
                    <th style="width: 15%">
                      <div class="col-sm-1">Users</div>
                    </th>
                    <th style="width: 40%">
                      <div class="col-sm-4">Notes</div>
                    </th>
                    <th style="width: 5%">
                      <div class="col-sm-1"></div>
                    </th>
                  </tr>
                </thead>

                <tbody>
                  {% for application in applications %}
                  <tr>
                    <td style="width: 2%">
                      <div class="col-sm-1">
                        <a href="{% url 'project:delete_application' project.id application.id %}"
                          class="btn btn-danger btn-sm">
                          <span class="glyphicon glyphicon-remove-sign"></span>
                        </a>
                      </div>
                    </td>
                    <td style="width: 3%">
                      <div class="col-sm-1">{{forloop.counter}}</div>
                    </td>
                    <td style="width: 15%">
                      <div class="col-sm-1">
                        <a href="{% url 'project:application_detail' project.id application.id %}">
                          {{application.name}}
                        </a>
                      </div>
                    </td>
                    <td style="width: 15%">
                      <div class="col-sm-1">{{application.access}}</div>
                    </td>
                    <td style="width: 15%">
                      <div class="col-sm-1">{{application.username}}</div>
                    </td>
                    <td style="width: 40%">
                      <div class="col-sm-4">{{application.notes}}</div>
                    </td>
                    <td style="width: 5%">
                      <div class="col-sm-1">100 %</div>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>

              </table>
            </div>

            <div class="row">
              <div class="col-sm-10">
                <a href="{% url 'project:create_application' project.id %}" class="btn btn-success btn-lg">
                  <span class="glyphicon glyphicon-plus-sign"></span> New Application
                </a>
              </div>
            </div>

          </div>

        </div>
      </div>

    </div>
  </div>
</div>

{% endblock %}

project/templates/project/projects.html
{% extends 'project/base.html' %}
{% block title %}Projects{% endblock %}
{% block projects_active %}active{% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1">

            {% for project in projects %}
            <div class="panel-group">
                <div class="panel panel-default">

                    <div class="panel-heading">
                        <div class="row">

                            <div class="col-sm-2">
                                <h3>
                                    <a href="{% url 'project:delete_project' project.id %}"
                                        class="btn btn-danger btn-sm">
                                        <span class="glyphicon glyphicon-remove-sign"></span> Remove
                                    </a>
                                </h3>
                            </div>

                            <div class="col-sm-3">
                                <h3><a href="{% url 'project:project_detail' project.id %}">{{project.name}}</a></h3>
                            </div>

                            <div class="col-sm-3">
                                <h3> {{project.situation}}</h3>
                            </div>

                            <div class="col-sm-2">
                                <h3>
                                    <a href="{% url 'project:report' project.id %}" class="btn btn-info btn-sm">
                                        <span class="glyphicon glyphicon-info-sign"></span> Report
                                    </a>
                                </h3>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
            {% endfor %}

            <a href="{% url 'project:create_project' %}" class="btn btn-success btn-lg">
                <span class="glyphicon glyphicon-plus-sign"></span> New Project
            </a>

        </div>
    </div>
</div>

{% endblock %}